services:
  api-gateway:
    image: ${API_GATEWAY_IMAGE_NAMETAG}
    container_name: quicket-api-gateway
    ports:
      - "8080:80"
    networks:
      - quicket-net
    depends_on:
      user-api:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      booking-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  quicket-redis:
    image: redis:8.2.2-alpine3.22
    container_name: quicket-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - redis_data:/data
  user-mysql:
    image: mysql:8.0.43-debian
    container_name: user-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${USER_MYSQL_DB_NAME}
      MYSQL_USER: ${USER_MYSQL_USER}
      MYSQL_PASSWORD: ${USER_MYSQL_PASSWORD}
    ports:
      - "${USER_MYSQL_EXTERNAL_PORT}:3306"
    volumes:
      - quicket-user-mysql:/var/lib/mysql
    networks:
      - quicket-net
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${USER_MYSQL_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  booking-mysql:
    image: mysql:8.0.43-debian
    container_name: booking-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${BOOKING_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${BOOKING_MYSQL_DB_NAME}
      MYSQL_USER: ${BOOKING_MYSQL_USER}
      MYSQL_PASSWORD: ${BOOKING_MYSQL_PASSWORD}
    ports:
      - "${BOOKING_MYSQL_EXTERNAL_PORT}:3306"
    volumes:
      - quicket-booking-mysql:/var/lib/mysql
    networks:
      - quicket-net
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${BOOKING_MYSQL_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5
      start_period: 30s
    networks:
      - quicket-net
networks:
  quicket-net:
    driver: bridge
    name: quicket-net
volumes:
  quicket-user-mysql:
  quicket-booking-mysql:
  rabbitmq_data:
  rabbitmq_logs:
  redis_data:
